---
title: "Experiment with single chromosome"
output: html_notebook
---


```{r}
library(devtools)
load_all()
```

```{r}
gc <- varbin.gc.20k
bin_mat <- example1.varbin.20k
```

```{r}
gc1 <- gc[gc$bin.chrom == 'chr1',]
bin_mat1 <- bin_mat[bin_mat$chrom=='chr1',]
```

```{r}
bin_mat_normalized1<- gc_one(bin_mat1,gc1)
bin_mat_segmented <- cbs.segment_one(bin_mat_normalized1, alpha = 0.05, nperm = 1000, undo.SD = 1.0, min.width = 5, method = "multiplier", genome = "hg" , graphic = TRUE)
```
```{r}
bin_mat1$bincount <- rep(10, 1567)
bin_mat_normalized1<- gc_one(bin_mat1,gc1)
bin_mat_segmented <- cbs.segment_one(bin_mat_normalized1, alpha = 0.05, nperm = 1000, undo.SD = 1.0, min.width = 5, method = "multiplier", genome = "hg" , graphic = TRUE)

```

```{r}
gc2 <- gc[gc$bin.chrom == 'chr2',]
bin_mat2 <- bin_mat[bin_mat$chrom=='chr2',]
dim(bin_mat2)
bin_mat_normalized2<- gc_one(bin_mat2,gc2)
bin_mat_segmented2 <- cbs.segment_one(bin_mat_normalized2, alpha = 0.05, nperm = 1000, undo.SD = 1.0, min.width = 5, method = "multiplier", genome = "hg" , graphic = TRUE)
```
```{r}
gc3 <- gc[gc$bin.chrom == 'chr3',]
bin_mat3 <- bin_mat[bin_mat$chrom=='chr3',]
dim(bin_mat3)
bin_mat_normalized3<- gc_one(bin_mat3,gc3)
bin_mat_segmented3 <- cbs.segment_one(bin_mat_normalized3, alpha = 0.05, nperm = 1000, undo.SD = 1.0, min.width = 5, method = "multiplier", genome = "hg" , graphic = TRUE)
```


```{r}
gc19 <- gc[gc$bin.chrom == 'chr19',]
bin_mat19 <- bin_mat[bin_mat$chrom=='chr19',]
dim(bin_mat19)
bin_mat_normalized19<- gc_one(bin_mat19,gc19)
bin_mat_segmented19 <- cbs.segment_one(bin_mat_normalized19, alpha = 0.05, nperm = 1000, undo.SD = 1.0, min.width = 5, method = "multiplier", genome = "hg" , graphic = TRUE)
```

```{r}
size19 = dim(bin_mat19)[1]
bin_mat19$bincount <- rep(10, size19)

bin_mat_normalized19<- gc_one(bin_mat19,gc19)
bin_mat_segmented19 <- cbs.segment_one(bin_mat_normalized19, alpha = 0.05, nperm = 1000, undo.SD = 1.0, min.width = 5, method = "multiplier", genome = "hg" , graphic = TRUE)
```
