---
title: "Experiment with single chromosome"
output: html_notebook
---


```{r}
library(devtools)
load_all()
```

```{r}
gc <- varbin.gc.20k
bin_mat <- example1.varbin.20k
```


```{r}
gc19 <- gc[gc$bin.chrom == 'chr19',]
bin_mat19 <- bin_mat[bin_mat$chrom=='chr19',]
dim(bin_mat19)
bin_mat_normalized19<- gc_one(bin_mat19,gc19)
bin_mat_segmented19 <- cbs.segment_one(bin_mat_normalized19, alpha = 0.05, nperm = 1000, 
                                       undo.SD = 1.0, min.width = 5, method = "multiplier", genome = "hg" , graphic = TRUE)
```

```{r}
size19 = dim(bin_mat19)[1]
bin_mat19$bincount <- rep(10, size19)

bin_mat_normalized19<- gc_one(bin_mat19,gc19)
bin_mat_segmented19 <- cbs.segment_one(bin_mat_normalized19, alpha = 0.05, nperm = 1000, 
                                       undo.SD = 1.0, min.width = 5, method = "multiplier", genome = "hg" , graphic = TRUE)
```


```{r}
bin_mat19$bincount <- c(rep(40, size19/2), rep(20, size19/2 + 1))
bin_mat_normalized19<- gc_one(bin_mat19,gc19)
bin_mat_segmented19 <- cbs.segment_one(bin_mat_normalized19, alpha = 0.05, nperm = 1000, 
                                       undo.SD = 1.0, min.width = 5, method = "multiplier", genome = "hg" , graphic = TRUE)
```
```{r}
gc19$gc.content = c(rep(0.5, size19/2), rep(0.55, size19/2+1))
bin_mat19$bincount <- c(rep(40, size19/2), rep(20, size19/2+1))
bin_mat_normalized19<- gc_one(bin_mat19, gc19)
bin_mat_segmented19 <- cbs.segment_one(bin_mat_normalized19, alpha = 0.05, nperm = 1000, 
                                       undo.SD = 1.0, min.width = 5, method = "multiplier", genome = "hg" , graphic = TRUE)

```
```{r}
gc19$gc.content = c(rep(0.2, size19/2), rep(0.8, size19/2), 0.8)
bin_mat19$bincount <- rep(100, size19)
bin_mat_normalized19<- gc_one(bin_mat19, gc19)
bin_mat_segmented19 <- cbs.segment_one(bin_mat_normalized19, alpha = 0.05, nperm = 1000, 
                                       undo.SD = 1.0, min.width = 5, method = "multiplier", genome = "hg" , graphic = TRUE)

```
```{r}
gc19$gc.content = c(rep(0.2, size19/2), rep(0.8, size19/2), 0.8)
bin_mat19$bincount <- c(rep(100, size19/2), rep(25, size19/2), 25)
bin_mat_normalized19<- gc_one(bin_mat19, gc19)
bin_mat_segmented19 <- cbs.segment_one(bin_mat_normalized19, alpha = 0.05, nperm = 1000, 
                                       undo.SD = 1.0, min.width = 5, method = "multiplier", genome = "hg" , graphic = TRUE)
```

